export const CANCEL = '__CANCEL__';
export const NOT_FOUND = '__NOTFOUND__';
export const ADD = 'ADD';
export const REMOVE = 'REMOVE';
export const PUBLIC_NUGET = 'Public NuGet';
export const emptyString = '';
export const ezNuget = 'ezNuget';
export const projFileExtensionsMatcher = /\.(cs|fs|vb)proj$/;
export const csProjGlobPattern = '**/*.csproj';